In [2]:
import pandas as pd
import numpy as np

 # Display only the Product Name and Price columns from the Products dataset.

In [4]:
sales = pd.read_csv("../../../Data/sales.csv")
products = pd.read_csv("../../../Data/products.csv")
stores = pd.read_csv("../../../Data/stores.csv")
category = pd.read_csv("../../../Data/category.csv")
warranty = pd.read_csv("../../../Data/warranty.csv")

In [7]:
products[["product_name" ,"price"]]

                     product_name  price
0         MacBook Pro (Touch Bar)   1499
1                         AirPods    159
2            iPad Pro (10.5-inch)    649
3   iPad Pro (12.9-inch, 2nd Gen)    799
4     MacBook Pro (13-inch, 2017)   1299
..                            ...    ...
59         iPad Pro (M2, 11-inch)    799
60       iPad Pro (M2, 12.9-inch)   1099
61                      iPhone 15    799
62                  iPhone 15 Pro    999
63              iPhone 15 Pro Max   1199

[64 rows x 2 columns]

# Display the first 20 rows and last 20 rows from the Sales dataset

In [13]:
sales.head(20)

       sale_id   sale_date store_id product_id  quantity
0   OID-358365  2021-09-16    ST-33       P-44         1
1   OID-358510  2022-01-28    ST-33       P-44         1
2   OID-358525  2021-11-26    ST-33       P-44         1
3   OID-358591  2021-09-15    ST-33       P-44         1
4   OID-358601  2022-02-07    ST-33       P-44         1
5   OID-358877  2022-03-10    ST-33       P-44         1
6   OID-358995  2022-04-05    ST-33       P-44         1
7   OID-358996  2021-11-22    ST-33       P-44         1
8   OID-359012  2022-03-28    ST-33       P-44         1
9   OID-359013  2022-02-08    ST-33       P-44         1
10  OID-359105  2021-09-20    ST-33       P-44         1
11  OID-359121  2022-04-02    ST-33       P-44         1
12  OID-359182  2022-03-08    ST-33       P-44         1
13  OID-359201  2021-09-06    ST-33       P-44         1
14  OID-359202  2022-01-19    ST-33       P-44         1
15  OID-359203  2022-03-23    ST-33       P-44         1
16  OID-359412  2022-03-10    ST-33       P-44         1
17  OID-359502  2021-11-04    ST-33       P-44         1
18  OID-359503  2022-01-09    ST-33       P-44         1
19  OID-359594  2022-01-16    ST-33       P-44         1

In [14]:
sales.tail(20)

            sale_id   sale_date store_id product_id  quantity
1040171  OID-358325  2022-03-29    ST-33       P-47         1
1040172  OID-358326  2022-01-02    ST-33       P-48         1
1040173  OID-358327  2022-01-22    ST-33       P-49         1
1040174  OID-358328  2022-04-19    ST-33       P-50         1
1040175  OID-358329  2022-05-06    ST-33       P-45         1
1040176  OID-358330  2022-03-26    ST-33       P-48         1
1040177  OID-358331  2021-12-14    ST-33       P-48         1
1040178  OID-358332  2021-12-04    ST-33       P-49         1
1040179  OID-358333  2022-09-26    ST-33       P-49         1
1040180  OID-358345  2022-07-21    ST-33       P-46         1
1040181  OID-358346  2022-05-31    ST-33       P-47         1
1040182  OID-358347  2022-06-21    ST-33       P-48         1
1040183  OID-358348  2022-07-04    ST-33       P-48         1
1040184  OID-358349  2022-08-13    ST-33       P-48         1
1040185  OID-358350  2022-02-16    ST-33       P-48         1
1040186  OID-358351  2022-08-11    ST-33       P-48         1
1040187  OID-358352  2022-02-06    ST-33       P-49         1
1040188  OID-358353  2022-05-27    ST-33       P-49         1
1040189  OID-358354  2022-03-22    ST-33       P-49         1
1040190  OID-358355  2022-07-19    ST-33       P-49         1

# Extract Sale ID , Product ID , Store ID , and Quantity using iloc[] .

In [15]:
sales.iloc[:, [0, 3, 2, 4]]

# Select columns using column positions

            sale_id product_id store_id  quantity
0        OID-358365       P-44    ST-33         1
1        OID-358510       P-44    ST-33         1
2        OID-358525       P-44    ST-33         1
3        OID-358591       P-44    ST-33         1
4        OID-358601       P-44    ST-33         1
...             ...        ...      ...       ...
1040186  OID-358351       P-48    ST-33         1
1040187  OID-358352       P-49    ST-33         1
1040188  OID-358353       P-49    ST-33         1
1040189  OID-358354       P-49    ST-33         1
1040190  OID-358355       P-49    ST-33         1

[1040191 rows x 4 columns]

# Top 20 for practise

In [16]:
sales.iloc[:20,[0,3,2,4]]

       sale_id product_id store_id  quantity
0   OID-358365       P-44    ST-33         1
1   OID-358510       P-44    ST-33         1
2   OID-358525       P-44    ST-33         1
3   OID-358591       P-44    ST-33         1
4   OID-358601       P-44    ST-33         1
5   OID-358877       P-44    ST-33         1
6   OID-358995       P-44    ST-33         1
7   OID-358996       P-44    ST-33         1
8   OID-359012       P-44    ST-33         1
9   OID-359013       P-44    ST-33         1
10  OID-359105       P-44    ST-33         1
11  OID-359121       P-44    ST-33         1
12  OID-359182       P-44    ST-33         1
13  OID-359201       P-44    ST-33         1
14  OID-359202       P-44    ST-33         1
15  OID-359203       P-44    ST-33         1
16  OID-359412       P-44    ST-33         1
17  OID-359502       P-44    ST-33         1
18  OID-359503       P-44    ST-33         1
19  OID-359594       P-44    ST-33         1

# Display only stores belonging to a selected country using loc[] .

In [24]:
stores.loc[stores["country"]=="UK"]

   store_id           store_name        city country
21    ST-22  Apple Regent Street      London      UK
22    ST-23  Apple Covent Garden      London      UK
23    ST-24      Apple Bluewater  Greenhithe      UK
66    ST-67     Apple Birmingham  Birmingham      UK
67    ST-68     Apple Manchester  Manchester      UK
68    ST-69      Apple Sheffield   Sheffield      UK
69    ST-70      Apple Newcastle   Newcastle      UK
70    ST-71          Apple Leeds       Leeds      UK
71    ST-72        Apple Bristol     Bristol      UK
72    ST-73        Apple Cardiff     Cardiff      UK

# Create a new DataFrame named sales_basic containing only Sale ID , Product ID , Store ID , and Quantity

In [28]:
sales_report = sales[["sale_id",
    "product_id",
    "store_id",
    "quantity"
]]
print(sales_report)

            sale_id product_id store_id  quantity
0        OID-358365       P-44    ST-33         1
1        OID-358510       P-44    ST-33         1
2        OID-358525       P-44    ST-33         1
3        OID-358591       P-44    ST-33         1
4        OID-358601       P-44    ST-33         1
...             ...        ...      ...       ...
1040186  OID-358351       P-48    ST-33         1
1040187  OID-358352       P-49    ST-33         1
1040188  OID-358353       P-49    ST-33         1
1040189  OID-358354       P-49    ST-33         1
1040190  OID-358355       P-49    ST-33         1

[1040191 rows x 4 columns]

# Business Insight:
 Efficient row and column selection helps analysts focus on relevant business
 information, improving performance and making reports easier to understand.