In [1]:
import pandas as pd
import numpy as np

In [2]:
sales = pd.read_csv("../../../Data/sales.csv")
products = pd.read_csv("../../../Data/products.csv")
stores = pd.read_csv("../../../Data/stores.csv")
category = pd.read_csv("../../../Data/category.csv")
warranty = pd.read_csv("../../../Data/warranty.csv")

Calculate the Running Total Revenue based on Sale Date.

In [16]:
master_sales = sales.merge(products, on="product_id")
master_sales = master_sales.merge(category, on="category_id")
master_sales = master_sales.merge(stores, on="store_id")
master_sales = master_sales.merge(warranty, on="sale_id")

# First make the master_sales DataFrame by merge all the dataframes together.

In [17]:
master_sales["revenue"] = master_sales["quantity"] * master_sales["price"]

# Calculate the Revenue Contribution of each store based on the total revenue.

In [19]:
master_sales = master_sales.sort_values("sale_date")

# Calculate the Running Total Revenue based on Sale Date.

In [21]:
master_sales["running_total_revenue"] = master_sales["revenue"].cumsum()

In [26]:
master_sales[["sale_date", "revenue", "running_total_revenue"]].head(10)

        sale_date  revenue  running_total_revenue
26816  2019-09-01     1998                   1998
26317  2019-09-01      699                   2697
26318  2019-09-01     1398                   4095
26502  2019-09-01     1398                   5493
26653  2019-09-01      987                   6480
26652  2019-09-01     2198                   8678
26316  2019-09-03      399                   9077
26501  2019-09-03      987                  10064
26500  2019-09-04      658                  10722
26815  2019-09-04     1197                  11919

Calculate a 7-Day Moving Average of Revenue

In [28]:
master_sales["moving_average"] = master_sales["revenue"].rolling(window=7).mean()

In [33]:
print(master_sales[["sale_date", "revenue", "moving_average"]].head(10))

        sale_date  revenue  moving_average
26816  2019-09-01     1998             NaN
26317  2019-09-01      699             NaN
26318  2019-09-01     1398             NaN
26502  2019-09-01     1398             NaN
26653  2019-09-01      987             NaN
26652  2019-09-01     2198             NaN
26316  2019-09-03      399     1296.714286
26501  2019-09-03      987     1152.285714
26500  2019-09-04      658     1146.428571
26815  2019-09-04     1197     1117.714286

Create a column showing the Previous Day Revenue using shift()

In [35]:
master_sales["previous_revenue"] = master_sales["revenue"].shift(1)

In [36]:
print(master_sales[["sale_date", "revenue", "previous_revenue"]].head(10))

        sale_date  revenue  previous_revenue
26816  2019-09-01     1998               NaN
26317  2019-09-01      699            1998.0
26318  2019-09-01     1398             699.0
26502  2019-09-01     1398            1398.0
26653  2019-09-01      987            1398.0
26652  2019-09-01     2198             987.0
26316  2019-09-03      399            2198.0
26501  2019-09-03      987             399.0
26500  2019-09-04      658             987.0
26815  2019-09-04     1197             658.0

Calculate the Revenue Growth (%) compared to the previous day

In [38]:
master_sales["revenue_growth"] = (
    (master_sales["revenue"] - master_sales["previous_revenue"])
    / master_sales["previous_revenue"]
) * 100

In [40]:
print(master_sales[["sale_date", "revenue", "previous_revenue", "revenue_growth"]].head(10))

        sale_date  revenue  previous_revenue  revenue_growth
26816  2019-09-01     1998               NaN             NaN
26317  2019-09-01      699            1998.0      -65.015015
26318  2019-09-01     1398             699.0      100.000000
26502  2019-09-01     1398            1398.0        0.000000
26653  2019-09-01      987            1398.0      -29.399142
26652  2019-09-01     2198             987.0      122.695035
26316  2019-09-03      399            2198.0      -81.847134
26501  2019-09-03      987             399.0      147.368421
26500  2019-09-04      658             987.0      -33.333333
26815  2019-09-04     1197             658.0       81.914894

Build a complete Sales Trend Report containing Date, Daily Revenue, Previous Revenue, Growth (%),
Running Revenue, and 7-Day Moving Average.

In [43]:
sales_trend = master_sales[
    [
        "sale_date",
        "revenue",
        "previous_revenue",
        "revenue_growth",
        "running_total_revenue",
        "moving_average"
    ]
]

sales_trend

,sale_date,revenue,previous_revenue,revenue_growth,running_total_revenue,moving_average
26816,2019-09-01,1998,NaN,NaN,1998,NaN
26317,2019-09-01,699,1998.0,-65.015015,2697,NaN
26318,2019-09-01,1398,699.0,100.000000,4095,NaN
26502,2019-09-01,1398,1398.0,0.000000,5493,NaN
26653,2019-09-01,987,1398.0,-29.399142,6480,NaN
...,...,...,...,...,...,...
3033,2023-12-31,399,399.0,0.000000,21543784,699.000000
3032,2023-12-31,399,399.0,0.000000,21543385,613.285714
3031,2023-12-31,399,399.0,0.000000,21542986,527.571429
3047,2023-12-31,179,399.0,-55.137845,21541888,453.285714
0,2023-12-31,399,179.0,122.905028,21576177,410.428571

# Business Insights

 1. Running Revenue helped track cumulative sales growth over time and monitor overall business performance.

 2. The 7-Day Moving Average reduced daily sales fluctuations and revealed the underlying revenue trend.

 3. Previous Day Revenue enabled day-to-day sales comparison and trend analysis.

 4. Revenue Growth (%) highlighted daily business growth or decline, making performance changes easier to identify.

 5. The Sales Trend Report combined multiple time-series metrics into a single dashboard-ready dataset for reporting and forecasting.